In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from google.colab import files
data = files.upload()

Saving archive (19).zip to archive (19).zip


In [ ]:
df = pd.read_csv('archive (19).zip')

In [ ]:
df

Unnamed: 0                                              title  \
0             0  COVID-19 Open Research Dataset Challenge (CORD...   
1             1               Animal Crossing New Horizons Catalog   
2             2                        Credit Card Fraud Detection   
3             3                        Netflix Movies and TV Shows   
4             4                    Novel Corona Virus 2019 Dataset   
..          ...                                                ...   
994         994                      Economic Freedom of the World   
995         995                    Zillow Rent Index, 2010-Present   
996         996                   The Interview Attendance Problem   
997         997                          US Population By Zip Code   
998         998                           British Birdsong Dataset   

                       uploaded_by           last_updated  usability  \
0          Allen Institute For AI     Updated 12 days ago        8.8   
1                      Jessica Li    Updated 7 months ago        8.2   
2    Machine Learning Group - ULB     Updated 4 years ago        8.5   
3                   Shivam Bansal    Updated 3 months ago       10.0   
4                             SRK    Updated 6 months ago        9.7   
..                             ...                    ...        ...   
994  Guillermina Sutter Schneider     Updated 3 years ago        7.4   
995                        Zillow     Updated 5 years ago        7.4   
996                VishnuRaghavan     Updated 4 years ago        7.9   
997              US Census Bureau     Updated 5 years ago        8.2   
998                Rachael Tatman     Updated 4 years ago        7.6   

                                 files     size  upvotes   badge  
0     558167 Files (JSON, CSV, other)     14 GB     9710    Gold  
1                      30 Files (CSV)    591 kB     9652    Gold  
2                        1 File (CSV)     69 MB     8712    Gold  
3                        1 File (CSV)      1 MB     6056    Gold  
4                       6 Files (CSV)      9 MB     5679    Gold  
..                                 ...      ...      ...     ...  
994                      1 File (CSV)    413 kB      114  Bronze  
995                     2 Files (CSV)      4 MB      114  Bronze  
996              2 Files (CSV, other)    127 kB      114  Silver  
997                     2 Files (CSV)     30 MB      114  Silver  
998            264 Files (other, CSV)    664 MB      115  Silver  

[999 rows x 9 columns]

In [ ]:
df.shape

(999, 9)

In [ ]:
df.columns

Index(['Unnamed: 0', 'title', 'uploaded_by', 'last_updated', 'usability',
       'files', 'size', 'upvotes', 'badge'],
      dtype='object')

In [ ]:
df.head()

Unnamed: 0                                              title  \
0           0  COVID-19 Open Research Dataset Challenge (CORD...   
1           1               Animal Crossing New Horizons Catalog   
2           2                        Credit Card Fraud Detection   
3           3                        Netflix Movies and TV Shows   
4           4                    Novel Corona Virus 2019 Dataset   

                     uploaded_by           last_updated  usability  \
0        Allen Institute For AI     Updated 12 days ago        8.8   
1                    Jessica Li    Updated 7 months ago        8.2   
2  Machine Learning Group - ULB     Updated 4 years ago        8.5   
3                 Shivam Bansal    Updated 3 months ago       10.0   
4                           SRK    Updated 6 months ago        9.7   

                               files     size  upvotes badge  
0   558167 Files (JSON, CSV, other)     14 GB     9710  Gold  
1                    30 Files (CSV)    591 kB     9652  Gold  
2                      1 File (CSV)     69 MB     8712  Gold  
3                      1 File (CSV)      1 MB     6056  Gold  
4                     6 Files (CSV)      9 MB     5679  Gold

In [ ]:
df.tail()

Unnamed: 0                             title  \
994         994     Economic Freedom of the World   
995         995   Zillow Rent Index, 2010-Present   
996         996  The Interview Attendance Problem   
997         997         US Population By Zip Code   
998         998          British Birdsong Dataset   

                       uploaded_by          last_updated  usability  \
994  Guillermina Sutter Schneider    Updated 3 years ago        7.4   
995                        Zillow    Updated 5 years ago        7.4   
996                VishnuRaghavan    Updated 4 years ago        7.9   
997              US Census Bureau    Updated 5 years ago        8.2   
998                Rachael Tatman    Updated 4 years ago        7.6   

                        files     size  upvotes   badge  
994             1 File (CSV)    413 kB      114  Bronze  
995            2 Files (CSV)      4 MB      114  Bronze  
996     2 Files (CSV, other)    127 kB      114  Silver  
997            2 Files (CSV)     30 MB      114  Silver  
998   264 Files (other, CSV)    664 MB      115  Silver

In [ ]:
df.describe()

Unnamed: 0   usability      upvotes
count  999.000000  999.000000   999.000000
mean   499.000000    8.123924   457.679680
std    288.530761    1.622493   789.305502
min      0.000000    1.200000   114.000000
25%    249.500000    7.100000   151.000000
50%    499.000000    8.200000   221.000000
75%    748.500000    9.700000   416.000000
max    998.000000   10.000000  9710.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 999 entries, 0 to 998
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Unnamed: 0    999 non-null    int64  
 1   title         999 non-null    object 
 2   uploaded_by   999 non-null    object 
 3   last_updated  999 non-null    object 
 4   usability     999 non-null    float64
 5   files         999 non-null    object 
 6   size          999 non-null    object 
 7   upvotes       999 non-null    int64  
 8   badge         999 non-null    object 
dtypes: float64(1), int64(2), object(6)
memory usage: 70.4+ KB


In [ ]:
df.isnull()

Unnamed: 0  title  uploaded_by  last_updated  usability  files   size  \
0         False  False        False         False      False  False  False   
1         False  False        False         False      False  False  False   
2         False  False        False         False      False  False  False   
3         False  False        False         False      False  False  False   
4         False  False        False         False      False  False  False   
..          ...    ...          ...           ...        ...    ...    ...   
994       False  False        False         False      False  False  False   
995       False  False        False         False      False  False  False   
996       False  False        False         False      False  False  False   
997       False  False        False         False      False  False  False   
998       False  False        False         False      False  False  False   

     upvotes  badge  
0      False  False  
1      False  False  
2      False  False  
3      False  False  
4      False  False  
..       ...    ...  
994    False  False  
995    False  False  
996    False  False  
997    False  False  
998    False  False  

[999 rows x 9 columns]

In [ ]:
df.isnull().sum()

Unnamed: 0      0
title           0
uploaded_by     0
last_updated    0
usability       0
files           0
size            0
upvotes         0
badge           0
dtype: int64

In [ ]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
df['title'] = label_encoder.fit_transform(df['title'])
df['title'].unique()
df

Unnamed: 0  title                    uploaded_by           last_updated  \
0             0    160        Allen Institute For AI     Updated 12 days ago   
1             1     75                    Jessica Li    Updated 7 months ago   
2             2    244  Machine Learning Group - ULB     Updated 4 years ago   
3             3    633                 Shivam Bansal    Updated 3 months ago   
4             4    646                           SRK    Updated 6 months ago   
..          ...    ...                            ...                    ...   
994         994    313  Guillermina Sutter Schneider     Updated 3 years ago   
995         995    960                        Zillow     Updated 5 years ago   
996         996    833                VishnuRaghavan     Updated 4 years ago   
997         997    899              US Census Bureau     Updated 5 years ago   
998         998    146                Rachael Tatman     Updated 4 years ago   

     usability                              files     size  upvotes   badge  
0          8.8   558167 Files (JSON, CSV, other)     14 GB     9710    Gold  
1          8.2                    30 Files (CSV)    591 kB     9652    Gold  
2          8.5                      1 File (CSV)     69 MB     8712    Gold  
3         10.0                      1 File (CSV)      1 MB     6056    Gold  
4          9.7                     6 Files (CSV)      9 MB     5679    Gold  
..         ...                                ...      ...      ...     ...  
994        7.4                      1 File (CSV)    413 kB      114  Bronze  
995        7.4                     2 Files (CSV)      4 MB      114  Bronze  
996        7.9              2 Files (CSV, other)    127 kB      114  Silver  
997        8.2                     2 Files (CSV)     30 MB      114  Silver  
998        7.6            264 Files (other, CSV)    664 MB      115  Silver  

[999 rows x 9 columns]

In [ ]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
df['uploaded_by'] = label_encoder.fit_transform(df['uploaded_by'])
df['uploaded_by'].unique()
df

Unnamed: 0  title  uploaded_by           last_updated  usability  \
0             0    160           35    Updated 12 days ago        8.8   
1             1     75          273   Updated 7 months ago        8.2   
2             2    244          334    Updated 4 years ago        8.5   
3             3    633          528   Updated 3 months ago       10.0   
4             4    646          499   Updated 6 months ago        9.7   
..          ...    ...          ...                    ...        ...   
994         994    313          222    Updated 3 years ago        7.4   
995         995    960          646    Updated 5 years ago        7.4   
996         996    833          618    Updated 4 years ago        7.9   
997         997    899          601    Updated 5 years ago        8.2   
998         998    146          467    Updated 4 years ago        7.6   

                                 files     size  upvotes   badge  
0     558167 Files (JSON, CSV, other)     14 GB     9710    Gold  
1                      30 Files (CSV)    591 kB     9652    Gold  
2                        1 File (CSV)     69 MB     8712    Gold  
3                        1 File (CSV)      1 MB     6056    Gold  
4                       6 Files (CSV)      9 MB     5679    Gold  
..                                 ...      ...      ...     ...  
994                      1 File (CSV)    413 kB      114  Bronze  
995                     2 Files (CSV)      4 MB      114  Bronze  
996              2 Files (CSV, other)    127 kB      114  Silver  
997                     2 Files (CSV)     30 MB      114  Silver  
998            264 Files (other, CSV)    664 MB      115  Silver  

[999 rows x 9 columns]

In [ ]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
df['last_updated'] = label_encoder.fit_transform(df['last_updated'])
df['last_updated'].unique()
df

Unnamed: 0  title  uploaded_by  last_updated  usability  \
0             0    160           35             1        8.8   
1             1     75          273            27        8.2   
2             2    244          334            19        8.5   
3             3    633          528            16       10.0   
4             4    646          499            24        9.7   
..          ...    ...          ...           ...        ...   
994         994    313          222            17        7.4   
995         995    960          646            22        7.4   
996         996    833          618            19        7.9   
997         997    899          601            22        8.2   
998         998    146          467            19        7.6   

                                 files     size  upvotes   badge  
0     558167 Files (JSON, CSV, other)     14 GB     9710    Gold  
1                      30 Files (CSV)    591 kB     9652    Gold  
2                        1 File (CSV)     69 MB     8712    Gold  
3                        1 File (CSV)      1 MB     6056    Gold  
4                       6 Files (CSV)      9 MB     5679    Gold  
..                                 ...      ...      ...     ...  
994                      1 File (CSV)    413 kB      114  Bronze  
995                     2 Files (CSV)      4 MB      114  Bronze  
996              2 Files (CSV, other)    127 kB      114  Silver  
997                     2 Files (CSV)     30 MB      114  Silver  
998            264 Files (other, CSV)    664 MB      115  Silver  

[999 rows x 9 columns]

In [ ]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
df['files'] = label_encoder.fit_transform(df['files'])
df['files'].unique()
df

Unnamed: 0  title  uploaded_by  last_updated  usability  files     size  \
0             0    160           35             1        8.8    227    14 GB   
1             1     75          273            27        8.2    147   591 kB   
2             2    244          334            19        8.5      0    69 MB   
3             3    633          528            16       10.0      0     1 MB   
4             4    646          499            24        9.7    233     9 MB   
..          ...    ...          ...           ...        ...    ...      ...   
994         994    313          222            17        7.4      0   413 kB   
995         995    960          646            22        7.4     80     4 MB   
996         996    833          618            19        7.9     82   127 kB   
997         997    899          601            22        8.2     80    30 MB   
998         998    146          467            19        7.6    128   664 MB   

     upvotes   badge  
0       9710    Gold  
1       9652    Gold  
2       8712    Gold  
3       6056    Gold  
4       5679    Gold  
..       ...     ...  
994      114  Bronze  
995      114  Bronze  
996      114  Silver  
997      114  Silver  
998      115  Silver  

[999 rows x 9 columns]

In [ ]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
df['size'] = label_encoder.fit_transform(df['size'])
df['size'].unique()
df

Unnamed: 0  title  uploaded_by  last_updated  usability  files  size  \
0             0    160           35             1        8.8    227    54   
1             1     75          273            27        8.2    147   331   
2             2    244          334            19        8.5      0   365   
3             3    633          528            16       10.0      0     1   
4             4    646          499            24        9.7    233   442   
..          ...    ...          ...           ...        ...    ...   ...   
994         994    313          222            17        7.4      0   245   
995         995    960          646            22        7.4     80   233   
996         996    833          618            19        7.9     82    39   
997         997    899          601            22        8.2     80   180   
998         998    146          467            19        7.6    128   359   

     upvotes   badge  
0       9710    Gold  
1       9652    Gold  
2       8712    Gold  
3       6056    Gold  
4       5679    Gold  
..       ...     ...  
994      114  Bronze  
995      114  Bronze  
996      114  Silver  
997      114  Silver  
998      115  Silver  

[999 rows x 9 columns]

In [ ]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
df['badge'] = label_encoder.fit_transform(df['badge'])
df['badge'].unique()
df

Unnamed: 0  title  uploaded_by  last_updated  usability  files  size  \
0             0    160           35             1        8.8    227    54   
1             1     75          273            27        8.2    147   331   
2             2    244          334            19        8.5      0   365   
3             3    633          528            16       10.0      0     1   
4             4    646          499            24        9.7    233   442   
..          ...    ...          ...           ...        ...    ...   ...   
994         994    313          222            17        7.4      0   245   
995         995    960          646            22        7.4     80   233   
996         996    833          618            19        7.9     82    39   
997         997    899          601            22        8.2     80   180   
998         998    146          467            19        7.6    128   359   

     upvotes  badge  
0       9710      1  
1       9652      1  
2       8712      1  
3       6056      1  
4       5679      1  
..       ...    ...  
994      114      0  
995      114      0  
996      114      2  
997      114      2  
998      115      2  

[999 rows x 9 columns]

In [ ]:
df1 = df.iloc[0:326,:]
df2 = df.iloc[327:653,:]
df3 = df.iloc[654:979,:]

In [ ]:
df1

Unnamed: 0  title  uploaded_by  last_updated  usability  files  size  \
0             0    160           35             1        8.8    227    54   
1             1     75          273            27        8.2    147   331   
2             2    244          334            19        8.5      0   365   
3             3    633          528            16       10.0      0     1   
4             4    646          499            24        9.7    233   442   
..          ...    ...          ...           ...        ...    ...   ...   
321         321     41          277            32        7.1    279   347   
322         322    404          358             7       10.0      3   178   
323         323     56          571             7        9.4     80   178   
324         324    434          523            22        8.5      0   463   
325         325    832          222            20        9.7    138     1   

     upvotes  badge  
0       9710      1  
1       9652      1  
2       8712      1  
3       6056      1  
4       5679      1  
..       ...    ...  
321      341      2  
322      341      2  
323      343      2  
324      340      1  
325      340      2  

[326 rows x 9 columns]

In [ ]:
df2

Unnamed: 0  title  uploaded_by  last_updated  usability  files  size  \
327         327     53          621            32       10.0    209   396   
328         328    776          176            19        7.4      0   262   
329         329    640            5            19        7.1     70   294   
330         330     88          605            19        5.9    140    65   
331         331    169           55            15        8.8      6   413   
..          ...    ...          ...           ...        ...    ...   ...   
648         648    767          692            17        7.5    225   431   
649         649    316          469            19        8.2    233   444   
650         650    435          484            17        6.5    264   158   
651         651    821           71             7       10.0      0     1   
652         652    362          584             7       10.0      0   288   

     upvotes  badge  
327      339      1  
328      339      2  
329      339      1  
330      337      2  
331      337      1  
..       ...    ...  
648      172      2  
649      172      2  
650      171      0  
651      171      1  
652      171      1  

[326 rows x 9 columns]

In [ ]:
df3

Unnamed: 0  title  uploaded_by  last_updated  usability  files  size  \
654         654    173          579            32        9.7    140   413   
655         655    327          251            32        9.7     80   423   
656         656    497          525            32        9.4     80     1   
657         657    468          150            17        8.5    138    55   
658         658    131           20             7        7.1    138    79   
..          ...    ...          ...           ...        ...    ...   ...   
974         974     22          680            19        7.5    149   243   
975         975    124          556            19        3.8     80   413   
976         976    969          696            19        4.1      0   443   
977         977      7          218            17        6.5    298   465   
978         978    682           72             7        8.1    247   112   

     upvotes  badge  
654      170      2  
655      171      2  
656      170      2  
657      170      2  
658      170      2  
..       ...    ...  
974      116      2  
975      116      2  
976      116      0  
977      116      2  
978      116      2  

[325 rows x 9 columns]

In [ ]:
x1 = df1.iloc[:,1:-1]
x1

title  uploaded_by  last_updated  usability  files  size  upvotes
0      160           35             1        8.8    227    54     9710
1       75          273            27        8.2    147   331     9652
2      244          334            19        8.5      0   365     8712
3      633          528            16       10.0      0     1     6056
4      646          499            24        9.7    233   442     5679
..     ...          ...           ...        ...    ...   ...      ...
321     41          277            32        7.1    279   347      341
322    404          358             7       10.0      3   178      341
323     56          571             7        9.4     80   178      343
324    434          523            22        8.5      0   463      340
325    832          222            20        9.7    138     1      340

[326 rows x 7 columns]

In [ ]:
y1 = df1.iloc[:,-1]
y1

0      1
1      1
2      1
3      1
4      1
      ..
321    2
322    2
323    2
324    1
325    2
Name: badge, Length: 326, dtype: int64

# **STANDARDIZATION**

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(df)
df_scale = pd.DataFrame(scaler.transform(df), columns=df1.columns)

In [ ]:
df_scale

Unnamed: 0     title  uploaded_by  last_updated  usability     files  \
0     -1.730318 -1.167723    -1.621936     -2.217849   0.416898  1.385559   
1     -1.726850 -1.465944    -0.432241      1.129804   0.046912  0.544710   
2     -1.723383 -0.873011    -0.127320      0.099757   0.231905 -1.000349   
3     -1.719915  0.491788     0.842431     -0.286511   1.156871 -1.000349   
4     -1.716448  0.537398     0.697469      0.743536   0.971878  1.448622   
..          ...       ...          ...           ...        ...       ...   
994    1.716448 -0.630926    -0.687176     -0.157755  -0.446404 -1.000349   
995    1.719915  1.639061     1.432280      0.486024  -0.446404 -0.159500   
996    1.723383  1.193484     1.292316      0.099757  -0.138081 -0.138479   
997    1.726850  1.425043     1.207338      0.486024   0.046912 -0.159500   
998    1.730318 -1.216842     0.537510      0.099757  -0.323075  0.345009   

         size    upvotes     badge  
0   -1.067676  11.727974 -0.484948  
1    0.899332  11.654455 -0.484948  
2    1.140770  10.462938 -0.484948  
3   -1.444035   7.096269 -0.484948  
4    1.687556   6.618395 -0.484948  
..        ...        ...       ...  
994  0.288636  -0.435638 -2.003641  
995  0.203423  -0.435638 -2.003641  
996 -1.174193  -0.435638  1.033745  
997 -0.172936  -0.435638  1.033745  
998  1.098163  -0.434371  1.033745  

[999 rows x 9 columns]

# **KNN classifier**

In [ ]:
from sklearn.model_selection import train_test_split
x1_train, x1_test, y1_train, y1_test = train_test_split(x1,y1,test_size=0.30,random_state=0)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=9, p=2)
classifier.fit(x1_train, y1_train)

KNeighborsClassifier(n_neighbors=9)

In [ ]:
y1_pred = classifier.predict(x1_test)

In [ ]:
from sklearn.metrics import confusion_matrix
cm1 = confusion_matrix(y1_test, y1_pred)

In [ ]:
cm1

array([[ 0,  1,  0],
       [ 0, 93,  0],
       [ 0,  4,  0]])

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

accuracy = accuracy_score(y1_test, y1_pred)
precision = precision_score(y1_test, y1_pred, average='macro')
recall = recall_score(y1_test, y1_pred, average='macro')
f1 = f1_score(y1_test, y1_pred, average='macro')

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("f1 Score:", f1)

Accuracy: 0.9489795918367347
Precision: 0.3163265306122449
Recall: 0.3333333333333333
f1 Score: 0.32460732984293195


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# **SVM**

In [ ]:
from sklearn.svm import SVC
svc = SVC()
svc.fit(x1_train, y1_train)

SVC()

In [ ]:
y1_pred = svc.predict(x1_test)

In [ ]:
from sklearn.metrics import confusion_matrix
cm1 = confusion_matrix(y1_test, y1_pred)

In [ ]:
cm1

array([[ 0,  1,  0],
       [ 0, 92,  0],
       [ 0,  5,  0]])

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

accuracy = accuracy_score(y1_test, y1_pred)
precision = precision_score(y1_test, y1_pred, average='macro')
recall = recall_score(y1_test, y1_pred, average='macro')
f1 = f1_score(y1_test, y1_pred, average='macro')

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("f1 Score:", f1)

Accuracy: 0.9387755102040817
Precision: 0.3129251700680272
Recall: 0.3333333333333333
f1 Score: 0.32280701754385965


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# **DECISION TREE**

In [ ]:
from sklearn.model_selection import train_test_split
x1_train, x1_test, y1_train, y1_test = train_test_split(x1, y1, test_size = 0.3, random_state = 1234, stratify=y1)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(random_state=1234)
dtc.fit(x1_train, y1_train)

DecisionTreeClassifier(random_state=1234)

In [ ]:
y1_pred = dtc.predict(x1_test)

In [ ]:
from sklearn.metrics import confusion_matrix
cm1 = confusion_matrix(y1_test, y1_pred)
score = dtc.score(x1_test, y1_test)

In [ ]:
cm1

array([[ 0,  1,  0],
       [ 0, 87,  5],
       [ 0,  4,  1]])

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

accuracy = accuracy_score(y1_test, y1_pred)
precision = precision_score(y1_test, y1_pred, average='macro')
recall = recall_score(y1_test, y1_pred, average='macro')
f1 = f1_score(y1_test, y1_pred, average='macro')

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("f1 Score:", f1)

Accuracy: 0.8979591836734694
Precision: 0.3707729468599034
Recall: 0.3818840579710145
f1 Score: 0.37582345191040845


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# **DF2**

In [ ]:
df2

Unnamed: 0  title  uploaded_by  last_updated  usability  files  size  \
327         327     53          621            32       10.0    209   396   
328         328    776          176            19        7.4      0   262   
329         329    640            5            19        7.1     70   294   
330         330     88          605            19        5.9    140    65   
331         331    169           55            15        8.8      6   413   
..          ...    ...          ...           ...        ...    ...   ...   
648         648    767          692            17        7.5    225   431   
649         649    316          469            19        8.2    233   444   
650         650    435          484            17        6.5    264   158   
651         651    821           71             7       10.0      0     1   
652         652    362          584             7       10.0      0   288   

     upvotes  badge  
327      339      1  
328      339      2  
329      339      1  
330      337      2  
331      337      1  
..       ...    ...  
648      172      2  
649      172      2  
650      171      0  
651      171      1  
652      171      1  

[326 rows x 9 columns]

In [ ]:
x2 = df2.iloc[:,1:-1]
x2

title  uploaded_by  last_updated  usability  files  size  upvotes
327     53          621            32       10.0    209   396      339
328    776          176            19        7.4      0   262      339
329    640            5            19        7.1     70   294      339
330     88          605            19        5.9    140    65      337
331    169           55            15        8.8      6   413      337
..     ...          ...           ...        ...    ...   ...      ...
648    767          692            17        7.5    225   431      172
649    316          469            19        8.2    233   444      172
650    435          484            17        6.5    264   158      171
651    821           71             7       10.0      0     1      171
652    362          584             7       10.0      0   288      171

[326 rows x 7 columns]

In [ ]:
y2= df2.iloc[:,-1]
y2

327    1
328    2
329    1
330    2
331    1
      ..
648    2
649    2
650    0
651    1
652    1
Name: badge, Length: 326, dtype: int64

**KNN**

In [ ]:
from sklearn.model_selection import train_test_split
x2_train, x2_test, y2_train, y2_test = train_test_split(x2,y2,test_size=0.30,random_state=0)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=9, p=2)
classifier.fit(x2_train, y2_train)

KNeighborsClassifier(n_neighbors=9)

In [ ]:
y2_pred = classifier.predict(x2_test)

In [ ]:
from sklearn.metrics import confusion_matrix
cm2 = confusion_matrix(y2_test, y2_pred)

In [ ]:
cm2

array([[ 0,  1,  2],
       [ 0, 11, 18],
       [ 0, 17, 49]])

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

accuracy = accuracy_score(y2_test, y2_pred)
precision = precision_score(y2_test, y2_pred, average='macro')
recall = recall_score(y2_test, y2_pred, average='macro')
f1 = f1_score(y2_test, y2_pred, average='macro')

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("f1 Score:", f1)

Accuracy: 0.6122448979591837
Precision: 0.3631517574546061
Recall: 0.3739115290839428
f1 Score: 0.3684120902511707


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


**SVM**

In [ ]:
from sklearn.svm import SVC
svc = SVC()
svc.fit(x2_train, y2_train)

SVC()

In [ ]:
y2_pred = svc.predict(x2_test)

In [ ]:
from sklearn.metrics import confusion_matrix
cm2 = confusion_matrix(y2_test, y2_pred)

In [ ]:
cm2

array([[ 0,  0,  3],
       [ 0,  1, 28],
       [ 0,  1, 65]])

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

accuracy = accuracy_score(y2_test, y2_pred)
precision = precision_score(y2_test, y2_pred, average='macro')
recall = recall_score(y2_test, y2_pred, average='macro')
f1 = f1_score(y2_test, y2_pred, average='macro')

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("f1 Score:", f1)

Accuracy: 0.673469387755102
Precision: 0.39236111111111116
Recall: 0.33977708115639155
f1 Score: 0.2889950882782424


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


**DECISION** **TREE**

In [ ]:
from sklearn.model_selection import train_test_split
x2_train, x2_test, y2_train, y2_test = train_test_split(x2, y2, test_size = 0.3, random_state = 1234, stratify=y2)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(random_state=1234)
dtc.fit(x2_train, y2_train)

DecisionTreeClassifier(random_state=1234)

In [ ]:
y2_predict = dtc.predict(x2_test)

In [ ]:
from sklearn.metrics import confusion_matrix
cm2 = confusion_matrix(y2_test, y2_predict)
score = dtc.score(x2_test, y2_test)

In [ ]:
cm2

array([[ 2,  0,  4],
       [ 0, 18, 13],
       [ 3, 22, 36]])

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

accuracy = accuracy_score(y2_test, y2_pred)
precision = precision_score(y2_test, y2_pred, average='macro')
recall = recall_score(y2_test, y2_pred, average='macro')
f1 = f1_score(y2_test, y2_pred, average='macro')

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("f1 Score:", f1)

Accuracy: 0.6224489795918368
Precision: 0.375
Recall: 0.33862154063105937
f1 Score: 0.2749790902657145


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# **DF3**

In [ ]:
df3

Unnamed: 0  title  uploaded_by  last_updated  usability  files  size  \
654         654    173          579            32        9.7    140   413   
655         655    327          251            32        9.7     80   423   
656         656    497          525            32        9.4     80     1   
657         657    468          150            17        8.5    138    55   
658         658    131           20             7        7.1    138    79   
..          ...    ...          ...           ...        ...    ...   ...   
974         974     22          680            19        7.5    149   243   
975         975    124          556            19        3.8     80   413   
976         976    969          696            19        4.1      0   443   
977         977      7          218            17        6.5    298   465   
978         978    682           72             7        8.1    247   112   

     upvotes  badge  
654      170      2  
655      171      2  
656      170      2  
657      170      2  
658      170      2  
..       ...    ...  
974      116      2  
975      116      2  
976      116      0  
977      116      2  
978      116      2  

[325 rows x 9 columns]

In [ ]:
x3 = df3.iloc[:,1:-1]
x3

title  uploaded_by  last_updated  usability  files  size  upvotes
654    173          579            32        9.7    140   413      170
655    327          251            32        9.7     80   423      171
656    497          525            32        9.4     80     1      170
657    468          150            17        8.5    138    55      170
658    131           20             7        7.1    138    79      170
..     ...          ...           ...        ...    ...   ...      ...
974     22          680            19        7.5    149   243      116
975    124          556            19        3.8     80   413      116
976    969          696            19        4.1      0   443      116
977      7          218            17        6.5    298   465      116
978    682           72             7        8.1    247   112      116

[325 rows x 7 columns]

In [ ]:
y3 = df3.iloc[:,-1]
y3

654    2
655    2
656    2
657    2
658    2
      ..
974    2
975    2
976    0
977    2
978    2
Name: badge, Length: 325, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
x3_train,x3_test,y3_train,y3_test=train_test_split(x3,y3,test_size=0.25,random_state=0)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=9, p=2)
classifier.fit(x3_train, y3_train)

KNeighborsClassifier(n_neighbors=9)

In [ ]:
y3_pred = classifier.predict(x3_test)

In [ ]:
from sklearn.metrics import confusion_matrix
cm3 = confusion_matrix(y3_test, y3_pred)

In [ ]:
cm3

array([[ 2,  0, 10],
       [ 2,  1, 14],
       [ 4,  3, 46]])

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

accuracy = accuracy_score(y3_test, y3_pred)
precision = precision_score(y3_test, y3_pred, average='macro')
recall = recall_score(y3_test, y3_pred, average='macro')
f1 = f1_score(y3_test, y3_pred, average='macro')

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("f1 Score:", f1)

Accuracy: 0.5975609756097561
Precision: 0.3857142857142857
Recall: 0.36447157479343933
f1 Score: 0.3477351916376306


**svc**

In [ ]:
from sklearn.svm import SVC
svc = SVC()
svc.fit(x3_train, y3_train)

SVC()

In [ ]:
y3_predict_svm = svc.predict(x3_test)

In [ ]:
from sklearn.metrics import confusion_matrix
cm3 = confusion_matrix(y3_test, y3_predict_svm)

In [ ]:
cm3

array([[ 0,  0, 12],
       [ 0,  0, 17],
       [ 0,  0, 53]])

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

accuracy = accuracy_score(y3_test, y3_pred)
precision = precision_score(y3_test, y3_pred, average='macro')
recall = recall_score(y3_test, y3_pred, average='macro')
f1 = f1_score(y3_test, y3_pred, average='macro')

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("f1 Score:", f1)

Accuracy: 0.5975609756097561
Precision: 0.3857142857142857
Recall: 0.36447157479343933
f1 Score: 0.3477351916376306


**decision tree**

In [ ]:
from sklearn.model_selection import train_test_split
x3_train, x3_test, y3_train, y3_test = train_test_split(x3, y3, test_size = 0.3, random_state = 1234)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(random_state=1234)
dtc.fit(x3_train, y3_train)

DecisionTreeClassifier(random_state=1234)

In [ ]:
y3_pred = dtc.predict(x3_test)

In [ ]:
from sklearn.metrics import confusion_matrix
cm3 = confusion_matrix(y3_test, y3_pred)
score = dtc.score(x3_test, y3_test)

In [ ]:
cm3

array([[12,  2, 13,  0],
       [ 2,  7,  6,  0],
       [13,  5, 37,  0],
       [ 0,  1,  0,  0]])

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

accuracy = accuracy_score(y3_test, y3_pred)
precision = precision_score(y3_test, y3_pred, average='macro')
recall = recall_score(y3_test, y3_pred, average='macro')
f1 = f1_score(y3_test, y3_pred, average='macro')

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("f1 Score:", f1)

Accuracy: 0.5714285714285714
Precision: 0.3929563492063492
Recall: 0.39595959595959596
f1 Score: 0.39444444444444443


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
